---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: trail3
  labels:
    env: dev
    app:  nginx
    version: "1.0"
spec: 





---
apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: trail2
spec:
  minReadySeconds: 30
  progressDeadlineseconds: 600
  replicas: 10
  selector:
    matchLabels:
      app: jenkins
    strategy: 
      type: RollingUpdate
      RollingUpdate:
        maxsurge: 40%
        maxUnavailable: 40%
    template:
      metadata: 
        labels:
          app: jenkins
          version: "1.0"
      spec:
        containers:
          - name: jenkins
            image: jenkins/jenkins:jdk-11
            resources: 
              
    
    
  